# Generated by Django 3.1.10 on 2023-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agre',
            field=models.ManyToManyField(null=True, to='erp.Aggregate', verbose_name='Agregados'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ing',
            field=models.ManyToManyField(null=True, to='erp.Ingredient', verbose_name='Ingrediente'),
        ),
    ]
