# Generated by Django 3.1.10 on 2023-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20230318_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agre',
            field=models.ManyToManyField(blank=True, to='erp.Aggregate', verbose_name='Agregados'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ing',
            field=models.ManyToManyField(blank=True, to='erp.Ingredient', verbose_name='Ingrediente'),
        ),
    ]
